### ISSUE TITLE
Getting a CORS preflight check error from my web application

### ISSUE THREAD

**Issue by aaka3207** [gbox-proxy/gbox#40]
First off, just wanted to say awesome work! I got this hitting my Hasura instance in Docker and the caching seems to works really well, even for nested types. I want to at least get this working and maybe slow roll into production if I can master what needs to be cached.

With that out of the way, I'm using docker-compose to run this with Hasura locally, as an API to my React app. I'm able to hit the playground just fine, but when I try to use it in my web app I get a CORS preflight error due to it missing the **access-control-allow-origin** header for my app.

I have my compose file configured like so, with localhost:3000 being the app:

![image](https://user-images.githubusercontent.com/16450271/182188093-48bd5584-55af-408b-8f8a-cb9e7e80c250.png)

I also examined the autosave.json file in the container and it's definitely picking up on my allowed origins:

![image](https://user-images.githubusercontent.com/16450271/182188330-4b6ab07a-92fb-4171-88e6-08091b2330c4.png)

Any help would be appreciated, thanks!

**Comment by vuongxuongminh** [comment]
Hey @aaka3207 your setting is correct, have you restart GBox service after update environment variables?

**Comment by aaka3207** [comment]
@vuongxuongminh Yes I restarted it but I still get this error from my browser:
![image](https://user-images.githubusercontent.com/16450271/182656052-c087d6af-d6d9-4b93-bee7-b15f8d7f42df.png)

Like I said the playground works fine.

**Comment by vuongxuongminh** [comment]
I had re-test with curl and everything play well:

```bash
curl http://localhost:8081/graphql -v -o /dev/null -XPOST -H "Origin: http://localhost:3000"  -H "Content-Type: application/json"
```
result:

```bash
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: http://localhost:3000
< Content-Type: application/json
< Server: Caddy
< Vary: Origin
< Date: Thu, 04 Aug 2022 00:49:33 GMT
< Content-Length: 56
```
Can you show me your docker-compose.yml?

**Comment by aaka3207** [comment]
Sure: there's not really much to share though, my GraphQL server runs just fine, I can hit gbox graphql playground just fine as well. 
![image](https://user-images.githubusercontent.com/16450271/182747581-82b4dcc6-7d2e-4ea6-a3a8-7f986a7add05.png)

I wonder if it's the fact that it's being requested from Chrome, and Chrome sends the preflight request. In which case it needs to send back that Access-Control-Allow-Origin: http://localhost:3000 header but it's not

**Comment by vuongxuongminh** [comment]
Hmm, maybe your browser had sent not allowed headers, could you copy Chrome request as curl for me?

**Comment by aaka3207** [comment]
I think I figured it out: Chrome sends a preflight request, which is an OPTIONS request. I tried to do this in CURL and now you don't see the allowed-origin headers

![image](https://user-images.githubusercontent.com/16450271/182887379-3d4b5a37-dae5-4f71-b7f5-87c7dcf4d08e.png)

**Comment by vuongxuongminh** [comment]
Hi @aaka3207, try to add referer header to cors_allowed_headers.

**Comment by aaka3207** [comment]
@vuongxuongminh I figured it out: I also send an _x-request-id_ header from my react client and it was rejecting that. I added that to cors_allowed_headers and it all works now!

**Comment by vuongxuongminh** [comment]
Great! Enjoy your day @aaka3207, if the GBox useful, please share it to Hasura community!
