### ISSUE TITLE
Possible to only cache specific fields?

### ISSUE THREAD

**Issue by aaka3207** [gbox-proxy/gbox#41]
Hi again,

I've been playing around with this for a little bit now and it's really promising. I want to try to put it in production, but I have a very large app with several fields and I want to take it slow. Specifically, I wanna start by caching only certain fields that I know need caching at this time, instead of my entire graph, and slowly test adding more and more. Is this possible currently?

**Comment by vuongxuongminh** [comment]
Hi,

GBox not support cache specific query fields but you can config cache by specific types check this: https://gbox-proxy.github.io/caching/concepts/rules#caddy-directive-types

**Comment by aaka3207** [comment]
@vuongxuongminh Yeah I saw that, but I could just turn off caching for all types except a few, could I? That's really the only thing keeping us from moving forward.

**Comment by vuongxuongminh** [comment]
Yes, you can, the default rule of GBox will cache all types of your schema, you can config cache only specific types and skip all another types, example:

```yaml
GBOX_CACHING_RULES: |
    book { # rule name it can be anything.
        types {
          Book # only cache query result have book types.
        }
        max_age 30m
        swr 30m
    }
```

The query results have another types will not affect, example:

```graphql
query GetUser {
   user {  # type of `user` field is `UserType`
      id
   }
}
```

**Comment by aaka3207** [comment]
Okay I will try it out. Thanks!

**Comment by vuongxuongminh** [comment]
Okay, reopen this issue if you need help.
