### ISSUE TITLE
Hasura support

### ISSUE THREAD

**Issue by mikeslattery** [gbox-proxy/gbox#43]
FEATURE: Support Hasura GraphQL queries.

Hasura's GraphQL engine exposes a postgres database as a GraphQL API.  It's GraphQL syntax differs a bit from what GBox supports.  The community edition of Hasura does not supply query caching and the Cloud and Enterprise editions only [supply simplistic caching](https://hasura.io/docs/latest/queries/response-caching/) (TTL invalidation only).

I think the only thing that's not compatible out of the box is auto-invalidation.

```graphql
query MyQuery {
  account(where: {id: {_eq: "1"}}) {
    id email role
  }
}

mutation MyMutation {
  insert_account(
      objects: {
        email: "m2@here.com",
        role: "admin"}) {
    returning {
      id
    }
  }

  update_account(
      where: {id: {_eq: "1"}},
      _set: {email: "m2@there.com"})

  delete_account(
    where: {id: {_eq: "1"}})
}
```

**Comment by vuongxuongminh** [comment]
You can use Hasura event trigger to purge caches via [admin api](https://gbox-proxy.github.io/caching/admin-api) when your tables are mutated.
